name: Backend Build

on:
  push:    
    branches:      
      - main  
  pull_request:    
    branches:      
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup JDK16
      uses: actions/setup-java@v3
      with:          
        distribution: 'adopt'          
        java-version: '16'

    - name: Build
      working-directory: backend        
      run: mvn package -DskipTests=true

    - name: Test
      working-directory: backend        
      run: mvn test

    - name: Checkstyle
      working-directory: backend
      run: mvn checkstyle:checkstyle

    - name: SpotBugs
      working-directory: backend
      continue-on-error: true
      run: mvn spotbugs:check
  